version: '3'

services:

  # ================= DEV CONFIG =================
  pacmusic-dev:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: pacmusic-dev
    networks:
      - pacmusic-network
    profiles:
      - Development

  # ================= STAGING CONFIG =================
  pacmusic-stg-1:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: pacmusic-stg-1
    restart: unless-stopped
    networks:
      - pacmusic-network
    profiles:
      - Staging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  pacmusic-stg-2:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: pacmusic-stg-2
    restart: unless-stopped
    networks:
      - pacmusic-network
    profiles:
      - Staging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ================= PRODUCTION CONFIG =================
  pacmusic-prod-1:
    image: "${APP_IMAGE}:${APP_TAG}"
    container_name: pacmusic-prod-1
    restart: unless-stopped
    networks:
      - pacmusic-network
    profiles:
      - Production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  pacmusic-prod-2:
    image: "${APP_IMAGE}:${APP_TAG}"
    container_name: pacmusic-prod-2
    restart: unless-stopped
    networks:
      - pacmusic-network
    profiles:
      - Production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ================= NGINX CONFIG =================
  pacmusic-nginx:
    image: nginx:stable
    container_name: pacmusic-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/html:/var/www/certbot:rw
      - ./nginx/ssl:/etc/letsencrypt:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - pacmusic-stg-1
      - pacmusic-stg-2
      - pacmusic-prod-1
      - pacmusic-prod-2
    networks:
      - pacmusic-network
    profiles:
      - Production
      - Staging

  # ================= CERTBOT CONFIG =================
  pacmusic-certbot:
    image: certbot/certbot
    container_name: pacmusic-certbot
    restart: unless-stopped
    volumes:
      - ./nginx/html:/var/www/certbot:rw
      - ./nginx/ssl:/etc/letsencrypt:rw
      - ./nginx/ssl/lib:/var/lib/letsencrypt:rw
    command: certonly --webroot -w /var/www/certbot --force-renewal --email ${EMAIL} --agree-tos -d cnc-code.site -d stg.cnc-code.site --agree-tos
    networks:
      - pacmusic-network
    profiles:
      - Production
      - Staging

networks:
  pacmusic-network:
    driver: bridge