name: Deploy Production

on:
  release:
    types: [published]

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to Production
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST_PRODUCTION }}
          username: ${{ secrets.SSH_USER_NAME_PRODUCTION }}
          key: ${{ secrets.SSH_PRIVAT_KEY_PRODUCTION }}
          script: |
            APP_PROD_PATH=${{ vars.APP_PROD_PATH }}
            APP_PROD_PORT=${{ secrets.APP_PROD_PORT }}

            if [[ -d "$APP_PROD_PATH" ]]; then
              cd $APP_PROD_PATH
              sudo docker compose down
              git pull --rebase
            else
              git clone $GIT_URL $APP_PROD_PATH
              cd $APP_PROD_PATH
            fi

            # Dummy .env
            echo "MINIO_ENDPOINT=dummy" > .env
            echo "MINIO_ACCESS_KEY=dummy" >> .env
            echo "MINIO_SECRET_KEY=dummy" >> .env
            echo "APP_PORT=$APP_PROD_PORT" >> .env

            # Deploy container
            sudo docker compose up pacmusic-prod --build --detach

            # Wait server
            for i in {1..20}; do
              if sudo docker exec pacmusic-prod curl -f http://localhost:$APP_PROD_PORT; then
                echo "✅ Production server ready"
                break
              else
                echo "⏳ Waiting... ($i/20)"
                sleep 5
              fi
            done

      - name: Test Production Endpoint
        run: |
          PROD_IP=${{ secrets.SSH_HOST_PRODUCTION }}
          for i in {1..20}; do
            if curl -f http://$PROD_IP >/dev/null 2>&1; then
              echo "✅ Production endpoint reachable!"
              break
            else
              echo "⏳ Waiting... ($i/20)"
              sleep 5
            fi
          done