name: Dev Testing

on:
  pull_request:
    branches:
      - "testing"

jobs:
  build-and-testing:
    name: Build and Test PacMusic
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .env
        run: |
          echo "MINIO_ENDPOINT=${{ secrets.MINIO_DEV_ENDPOINT }}" > .env
          echo "MINIO_ACCESS_KEY=${{ secrets.MINIO_DEV_ACCESS_KEY }}" >> .env
          echo "MINIO_SECRET_KEY=${{ secrets.MINIO_DEV_SECRET_KEY }}" >> .env
          echo "APP_PORT=5000" >> .env
          cat .env

      - name: Stop Previous Containers
        run: sudo docker compose --profile Development down || true

      - name: Build and Run Docker Containers
        run: sudo docker compose --profile Development up --build --detach pacmusic-dev

      - name: Wait for pacmusic-dev server
        run: |
          for i in {1..20}; do
            if curl -f http://localhost:5001 >/dev/null 2>&1; then
              echo "✅ Server is up!"
              break
            else
              echo "⏳ Waiting for server... ($i/20)"
              sleep 5
            fi
          done

      - name: Show container logs
        run: sudo docker logs pacmusic-dev --tail 20 || true

      - name: Run Tests
        run: python3 testing/test.py

      - name: Stop Containers
        if: always()
        run: sudo docker compose --profile Development down